
-- --------------------------------------------------------

--
-- Структура таблицы `gnm9x_setting`
--

CREATE TABLE IF NOT EXISTS `gnm9x_setting` (
  `setting_id` int(11) NOT NULL AUTO_INCREMENT,
  `store_id` int(11) NOT NULL DEFAULT '0',
  `code` varchar(128) NOT NULL,
  `key` varchar(128) NOT NULL,
  `value` text NOT NULL,
  `serialized` tinyint(1) NOT NULL,
  PRIMARY KEY (`setting_id`)
) ENGINE=InnoDB AUTO_INCREMENT=205 DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `gnm9x_setting`
--

INSERT INTO `gnm9x_setting` (`setting_id`, `store_id`, `code`, `key`, `value`, `serialized`) VALUES
(1, 0, 'config', 'config_robots', 'abot\r\ndbot\r\nebot\r\nhbot\r\nkbot\r\nlbot\r\nmbot\r\nnbot\r\nobot\r\npbot\r\nrbot\r\nsbot\r\ntbot\r\nvbot\r\nybot\r\nzbot\r\nbot.\r\nbot/\r\n_bot\r\n.bot\r\n/bot\r\n-bot\r\n:bot\r\n(bot\r\ncrawl\r\nslurp\r\nspider\r\nseek\r\naccoona\r\nacoon\r\nadressendeutschland\r\nah-ha.com\r\nahoy\r\naltavista\r\nananzi\r\nanthill\r\nappie\r\narachnophilia\r\narale\r\naraneo\r\naranha\r\narchitext\r\naretha\r\narks\r\nasterias\r\natlocal\r\natn\r\natomz\r\naugurfind\r\nbackrub\r\nbannana_bot\r\nbaypup\r\nbdfetch\r\nbig brother\r\nbiglotron\r\nbjaaland\r\nblackwidow\r\nblaiz\r\nblog\r\nblo.\r\nbloodhound\r\nboitho\r\nbooch\r\nbradley\r\nbutterfly\r\ncalif\r\ncassandra\r\nccubee\r\ncfetch\r\ncharlotte\r\nchurl\r\ncienciaficcion\r\ncmc\r\ncollective\r\ncomagent\r\ncombine\r\ncomputingsite\r\ncsci\r\ncurl\r\ncusco\r\ndaumoa\r\ndeepindex\r\ndelorie\r\ndepspid\r\ndeweb\r\ndie blinde kuh\r\ndigger\r\nditto\r\ndmoz\r\ndocomo\r\ndownload express\r\ndtaagent\r\ndwcp\r\nebiness\r\nebingbong\r\ne-collector\r\nejupiter\r\nemacs-w3 search engine\r\nesther\r\nevliya celebi\r\nezresult\r\nfalcon\r\nfelix ide\r\nferret\r\nfetchrover\r\nfido\r\nfindlinks\r\nfireball\r\nfish search\r\nfouineur\r\nfunnelweb\r\ngazz\r\ngcreep\r\ngenieknows\r\ngetterroboplus\r\ngeturl\r\nglx\r\ngoforit\r\ngolem\r\ngrabber\r\ngrapnel\r\ngralon\r\ngriffon\r\ngromit\r\ngrub\r\ngulliver\r\nhamahakki\r\nharvest\r\nhavindex\r\nhelix\r\nheritrix\r\nhku www octopus\r\nhomerweb\r\nhtdig\r\nhtml index\r\nhtml_analyzer\r\nhtmlgobble\r\nhubater\r\nhyper-decontextualizer\r\nia_archiver\r\nibm_planetwide\r\nichiro\r\niconsurf\r\niltrovatore\r\nimage.kapsi.net\r\nimagelock\r\nincywincy\r\nindexer\r\ninfobee\r\ninformant\r\ningrid\r\ninktomisearch.com\r\ninspector web\r\nintelliagent\r\ninternet shinchakubin\r\nip3000\r\niron33\r\nisraeli-search\r\nivia\r\njack\r\njakarta\r\njavabee\r\njetbot\r\njumpstation\r\nkatipo\r\nkdd-explorer\r\nkilroy\r\nknowledge\r\nkototoi\r\nkretrieve\r\nlabelgrabber\r\nlachesis\r\nlarbin\r\nlegs\r\nlibwww\r\nlinkalarm\r\nlink validator\r\nlinkscan\r\nlockon\r\nlwp\r\nlycos\r\nmagpie\r\nmantraagent\r\nmapoftheinternet\r\nmarvin/\r\nmattie\r\nmediafox\r\nmediapartners\r\nmercator\r\nmerzscope\r\nmicrosoft url control\r\nminirank\r\nmiva\r\nmj12\r\nmnogosearch\r\nmoget\r\nmonster\r\nmoose\r\nmotor\r\nmultitext\r\nmuncher\r\nmuscatferret\r\nmwd.search\r\nmyweb\r\nnajdi\r\nnameprotect\r\nnationaldirectory\r\nnazilla\r\nncsa beta\r\nnec-meshexplorer\r\nnederland.zoek\r\nnetcarta webmap engine\r\nnetmechanic\r\nnetresearchserver\r\nnetscoop\r\nnewscan-online\r\nnhse\r\nnokia6682/\r\nnomad\r\nnoyona\r\nnutch\r\nnzexplorer\r\nobjectssearch\r\noccam\r\nomni\r\nopen text\r\nopenfind\r\nopenintelligencedata\r\norb search\r\nosis-project\r\npack rat\r\npageboy\r\npagebull\r\npage_verifier\r\npanscient\r\nparasite\r\npartnersite\r\npatric\r\npear.\r\npegasus\r\nperegrinator\r\npgp key agent\r\nphantom\r\nphpdig\r\npicosearch\r\npiltdownman\r\npimptrain\r\npinpoint\r\npioneer\r\npiranha\r\nplumtreewebaccessor\r\npogodak\r\npoirot\r\npompos\r\npoppelsdorf\r\npoppi\r\npopular iconoclast\r\npsycheclone\r\npublisher\r\npython\r\nrambler\r\nraven search\r\nroach\r\nroad runner\r\nroadhouse\r\nrobbie\r\nrobofox\r\nrobozilla\r\nrules\r\nsalty\r\nsbider\r\nscooter\r\nscoutjet\r\nscrubby\r\nsearch.\r\nsearchprocess\r\nsemanticdiscovery\r\nsenrigan\r\nsg-scout\r\nshai\'hulud\r\nshark\r\nshopwiki\r\nsidewinder\r\nsift\r\nsilk\r\nsimmany\r\nsite searcher\r\nsite valet\r\nsitetech-rover\r\nskymob.com\r\nsleek\r\nsmartwit\r\nsna-\r\nsnappy\r\nsnooper\r\nsohu\r\nspeedfind\r\nsphere\r\nsphider\r\nspinner\r\nspyder\r\nsteeler/\r\nsuke\r\nsuntek\r\nsupersnooper\r\nsurfnomore\r\nsven\r\nsygol\r\nszukacz\r\ntach black widow\r\ntarantula\r\ntempleton\r\n/teoma\r\nt-h-u-n-d-e-r-s-t-o-n-e\r\ntheophrastus\r\ntitan\r\ntitin\r\ntkwww\r\ntoutatis\r\nt-rex\r\ntutorgig\r\ntwiceler\r\ntwisted\r\nucsd\r\nudmsearch\r\nurl check\r\nupdated\r\nvagabondo\r\nvalkyrie\r\nverticrawl\r\nvictoria\r\nvision-search\r\nvolcano\r\nvoyager/\r\nvoyager-hc\r\nw3c_validator\r\nw3m2\r\nw3mir\r\nwalker\r\nwallpaper\r\nwanderer\r\nwauuu\r\nwavefire\r\nweb core\r\nweb hopper\r\nweb wombat\r\nwebbandit\r\nwebcatcher\r\nwebcopy\r\nwebfoot\r\nweblayers\r\nweblinker\r\nweblog monitor\r\nwebmirror\r\nwebmonkey\r\nwebquest\r\nwebreaper\r\nwebsitepulse\r\nwebsnarf\r\nwebstolperer\r\nwebvac\r\nwebwalk\r\nwebwatch\r\nwebwombat\r\nwebzinger\r\nwhizbang\r\nwhowhere\r\nwild ferret\r\nworldlight\r\nwwwc\r\nwwwster\r\nxenu\r\nxget\r\nxift\r\nxirq\r\nyandex\r\nyanga\r\nyeti\r\nyodao\r\nzao\r\nzippp\r\nzyborg', 0),
(2, 0, 'config', 'config_shared', '0', 0),
(3, 0, 'config', 'config_secure', '0', 0),
(4, 0, 'config', 'config_fraud_detection', '0', 0),
(5, 0, 'config', 'config_ftp_status', '0', 0),
(6, 0, 'config', 'config_ftp_root', '', 0),
(7, 0, 'config', 'config_ftp_password', '', 0),
(8, 0, 'config', 'config_ftp_username', '', 0),
(9, 0, 'config', 'config_ftp_port', '21', 0),
(10, 0, 'config', 'config_ftp_hostname', '', 0),
(11, 0, 'config', 'config_meta_title', 'Your Store', 0),
(12, 0, 'config', 'config_meta_description', 'My Store', 0),
(13, 0, 'config', 'config_meta_keyword', '', 0),
(14, 0, 'config', 'config_theme', 'default', 0),
(15, 0, 'config', 'config_layout_id', '4', 0),
(16, 0, 'config', 'config_country_id', '222', 0),
(17, 0, 'config', 'config_zone_id', '3563', 0),
(18, 0, 'config', 'config_timezone', 'UTC', 0),
(19, 0, 'config', 'config_language', 'en-gb', 0),
(20, 0, 'config', 'config_admin_language', 'en-gb', 0),
(21, 0, 'config', 'config_currency', 'USD', 0),
(22, 0, 'config', 'config_currency_auto', '1', 0),
(23, 0, 'config', 'config_length_class_id', '1', 0),
(24, 0, 'config', 'config_weight_class_id', '1', 0),
(25, 0, 'config', 'config_product_count', '1', 0),
(26, 0, 'config', 'config_limit_admin', '20', 0),
(27, 0, 'config', 'config_review_status', '1', 0),
(28, 0, 'config', 'config_review_guest', '1', 0),
(29, 0, 'config', 'config_voucher_min', '1', 0),
(30, 0, 'config', 'config_voucher_max', '1000', 0),
(31, 0, 'config', 'config_tax', '1', 0),
(32, 0, 'config', 'config_tax_default', 'shipping', 0),
(33, 0, 'config', 'config_tax_customer', 'shipping', 0),
(34, 0, 'config', 'config_customer_online', '0', 0),
(35, 0, 'config', 'config_customer_activity', '0', 0),
(36, 0, 'config', 'config_customer_search', '0', 0),
(37, 0, 'config', 'config_customer_group_id', '1', 0),
(38, 0, 'config', 'config_customer_group_display', '[\"1\"]', 1),
(39, 0, 'config', 'config_customer_price', '0', 0),
(40, 0, 'config', 'config_account_id', '3', 0),
(41, 0, 'config', 'config_invoice_prefix', 'INV-2023-00', 0),
(43, 0, 'config', 'config_cart_weight', '1', 0),
(44, 0, 'config', 'config_checkout_guest', '1', 0),
(45, 0, 'config', 'config_checkout_id', '5', 0),
(46, 0, 'config', 'config_order_status_id', '1', 0),
(47, 0, 'config', 'config_processing_status', '[\"5\",\"1\",\"2\",\"12\",\"3\"]', 1),
(48, 0, 'config', 'config_complete_status', '[\"5\",\"3\"]', 1),
(49, 0, 'config', 'config_stock_display', '0', 0),
(50, 0, 'config', 'config_stock_warning', '0', 0),
(51, 0, 'config', 'config_stock_checkout', '0', 0),
(52, 0, 'config', 'config_affiliate_approval', '0', 0),
(53, 0, 'config', 'config_affiliate_auto', '0', 0),
(54, 0, 'config', 'config_affiliate_commission', '5', 0),
(55, 0, 'config', 'config_affiliate_id', '4', 0),
(56, 0, 'config', 'config_return_id', '0', 0),
(57, 0, 'config', 'config_return_status_id', '2', 0),
(58, 0, 'config', 'config_logo', 'catalog/opencart-logo.png', 0),
(59, 0, 'config', 'config_icon', 'catalog/cart.png', 0),
(60, 0, 'config', 'config_comment', '', 0),
(61, 0, 'config', 'config_open', '', 0),
(62, 0, 'config', 'config_image', '', 0),
(63, 0, 'config', 'config_fax', '', 0),
(64, 0, 'config', 'config_telephone', '123456789', 0),
(66, 0, 'config', 'config_geocode', '', 0),
(67, 0, 'config', 'config_owner', 'Your Name', 0),
(68, 0, 'config', 'config_address', 'Address 1', 0),
(69, 0, 'config', 'config_name', 'Your Store', 0),
(70, 0, 'config', 'config_seo_url', '0', 0),
(71, 0, 'config', 'config_file_max_size', '300000', 0),
(72, 0, 'config', 'config_file_ext_allowed', 'zip\r\ntxt\r\npng\r\njpe\r\njpeg\r\njpg\r\ngif\r\nbmp\r\nico\r\ntiff\r\ntif\r\nsvg\r\nsvgz\r\nzip\r\nrar\r\nmsi\r\ncab\r\nmp3\r\nqt\r\nmov\r\npdf\r\npsd\r\nai\r\neps\r\nps\r\ndoc', 0),
(73, 0, 'config', 'config_file_mime_allowed', 'text/plain\r\nimage/png\r\nimage/jpeg\r\nimage/gif\r\nimage/bmp\r\nimage/tiff\r\nimage/svg+xml\r\napplication/zip\r\n&quot;application/zip&quot;\r\napplication/x-zip\r\n&quot;application/x-zip&quot;\r\napplication/x-zip-compressed\r\n&quot;application/x-zip-compressed&quot;\r\napplication/rar\r\n&quot;application/rar&quot;\r\napplication/x-rar\r\n&quot;application/x-rar&quot;\r\napplication/x-rar-compressed\r\n&quot;application/x-rar-compressed&quot;\r\napplication/octet-stream\r\n&quot;application/octet-stream&quot;\r\naudio/mpeg\r\nvideo/quicktime\r\napplication/pdf', 0),
(74, 0, 'config', 'config_maintenance', '0', 0),
(75, 0, 'config', 'config_password', '1', 0),
(77, 0, 'config', 'config_compression', '0', 0),
(78, 0, 'config', 'config_error_display', '1', 0),
(79, 0, 'config', 'config_error_log', '1', 0),
(80, 0, 'config', 'config_error_filename', 'error.log', 0),
(81, 0, 'config', 'config_google_analytics', '', 0),
(82, 0, 'config', 'config_mail_engine', 'mail', 0),
(83, 0, 'config', 'config_mail_parameter', '', 0),
(84, 0, 'config', 'config_mail_smtp_hostname', '', 0),
(85, 0, 'config', 'config_mail_smtp_username', '', 0),
(86, 0, 'config', 'config_mail_smtp_password', '', 0),
(87, 0, 'config', 'config_mail_smtp_port', '25', 0),
(88, 0, 'config', 'config_mail_smtp_timeout', '5', 0),
(89, 0, 'config', 'config_mail_alert_email', '', 0),
(90, 0, 'config', 'config_mail_alert', '[\"order\"]', 1),
(91, 0, 'config', 'config_captcha', 'basic', 0),
(92, 0, 'config', 'config_captcha_page', '[\"review\",\"return\",\"contact\"]', 1),
(93, 0, 'config', 'config_login_attempts', '5', 0),
(94, 0, 'payment_free_checkout', 'payment_free_checkout_status', '1', 0),
(95, 0, 'payment_free_checkout', 'payment_free_checkout_order_status_id', '1', 0),
(96, 0, 'payment_free_checkout', 'payment_free_checkout_sort_order', '1', 0),
(97, 0, 'payment_cod', 'payment_cod_sort_order', '5', 0),
(98, 0, 'payment_cod', 'payment_cod_total', '0.01', 0),
(99, 0, 'payment_cod', 'payment_cod_order_status_id', '1', 0),
(100, 0, 'payment_cod', 'payment_cod_geo_zone_id', '0', 0),
(101, 0, 'payment_cod', 'payment_cod_status', '1', 0),
(102, 0, 'shipping_flat', 'shipping_flat_sort_order', '1', 0),
(103, 0, 'shipping_flat', 'shipping_flat_status', '1', 0),
(104, 0, 'shipping_flat', 'shipping_flat_geo_zone_id', '0', 0),
(105, 0, 'shipping_flat', 'shipping_flat_tax_class_id', '9', 0),
(106, 0, 'shipping_flat', 'shipping_flat_cost', '5.00', 0),
(107, 0, 'total_shipping', 'total_shipping_sort_order', '3', 0),
(108, 0, 'total_sub_total', 'total_sub_total_sort_order', '1', 0),
(109, 0, 'total_sub_total', 'total_sub_total_status', '1', 0),
(110, 0, 'total_tax', 'total_tax_status', '1', 0),
(111, 0, 'total_total', 'total_total_sort_order', '9', 0),
(112, 0, 'total_total', 'total_total_status', '1', 0),
(113, 0, 'total_tax', 'total_tax_sort_order', '5', 0),
(114, 0, 'total_credit', 'total_credit_sort_order', '7', 0),
(115, 0, 'total_credit', 'total_credit_status', '1', 0),
(116, 0, 'total_reward', 'total_reward_sort_order', '2', 0),
(117, 0, 'total_reward', 'total_reward_status', '1', 0),
(118, 0, 'total_shipping', 'total_shipping_status', '1', 0),
(119, 0, 'total_shipping', 'total_shipping_estimator', '1', 0),
(120, 0, 'total_coupon', 'total_coupon_sort_order', '4', 0),
(121, 0, 'total_coupon', 'total_coupon_status', '1', 0),
(122, 0, 'total_voucher', 'total_voucher_sort_order', '8', 0),
(123, 0, 'total_voucher', 'total_voucher_status', '1', 0),
(124, 0, 'module_category', 'module_category_status', '1', 0),
(125, 0, 'module_account', 'module_account_status', '1', 0),
(126, 0, 'theme_default', 'theme_default_product_limit', '15', 0),
(127, 0, 'theme_default', 'theme_default_product_description_length', '100', 0),
(128, 0, 'theme_default', 'theme_default_image_thumb_width', '228', 0),
(129, 0, 'theme_default', 'theme_default_image_thumb_height', '228', 0),
(130, 0, 'theme_default', 'theme_default_image_popup_width', '500', 0),
(131, 0, 'theme_default', 'theme_default_image_popup_height', '500', 0),
(132, 0, 'theme_default', 'theme_default_image_category_width', '80', 0),
(133, 0, 'theme_default', 'theme_default_image_category_height', '80', 0),
(134, 0, 'theme_default', 'theme_default_image_product_width', '228', 0),
(135, 0, 'theme_default', 'theme_default_image_product_height', '228', 0),
(136, 0, 'theme_default', 'theme_default_image_additional_width', '74', 0),
(137, 0, 'theme_default', 'theme_default_image_additional_height', '74', 0),
(138, 0, 'theme_default', 'theme_default_image_related_width', '200', 0),
(139, 0, 'theme_default', 'theme_default_image_related_height', '200', 0),
(140, 0, 'theme_default', 'theme_default_image_compare_width', '90', 0),
(141, 0, 'theme_default', 'theme_default_image_compare_height', '90', 0),
(142, 0, 'theme_default', 'theme_default_image_wishlist_width', '47', 0),
(143, 0, 'theme_default', 'theme_default_image_wishlist_height', '47', 0),
(144, 0, 'theme_default', 'theme_default_image_cart_height', '47', 0),
(145, 0, 'theme_default', 'theme_default_image_cart_width', '47', 0),
(146, 0, 'theme_default', 'theme_default_image_location_height', '50', 0),
(147, 0, 'theme_default', 'theme_default_image_location_width', '268', 0),
(148, 0, 'theme_default', 'theme_default_directory', 'default', 0),
(149, 0, 'theme_default', 'theme_default_status', '1', 0),
(150, 0, 'dashboard_activity', 'dashboard_activity_status', '1', 0),
(151, 0, 'dashboard_activity', 'dashboard_activity_sort_order', '7', 0),
(152, 0, 'dashboard_sale', 'dashboard_sale_status', '1', 0),
(153, 0, 'dashboard_sale', 'dashboard_sale_width', '3', 0),
(154, 0, 'dashboard_chart', 'dashboard_chart_status', '1', 0),
(155, 0, 'dashboard_chart', 'dashboard_chart_width', '6', 0),
(156, 0, 'dashboard_customer', 'dashboard_customer_status', '1', 0),
(157, 0, 'dashboard_customer', 'dashboard_customer_width', '3', 0),
(158, 0, 'dashboard_map', 'dashboard_map_status', '1', 0),
(159, 0, 'dashboard_map', 'dashboard_map_width', '6', 0),
(160, 0, 'dashboard_online', 'dashboard_online_status', '1', 0),
(161, 0, 'dashboard_online', 'dashboard_online_width', '3', 0),
(162, 0, 'dashboard_order', 'dashboard_order_sort_order', '1', 0),
(163, 0, 'dashboard_order', 'dashboard_order_status', '1', 0),
(164, 0, 'dashboard_order', 'dashboard_order_width', '3', 0),
(165, 0, 'dashboard_sale', 'dashboard_sale_sort_order', '2', 0),
(166, 0, 'dashboard_customer', 'dashboard_customer_sort_order', '3', 0),
(167, 0, 'dashboard_online', 'dashboard_online_sort_order', '4', 0),
(168, 0, 'dashboard_map', 'dashboard_map_sort_order', '5', 0),
(169, 0, 'dashboard_chart', 'dashboard_chart_sort_order', '6', 0),
(170, 0, 'dashboard_recent', 'dashboard_recent_status', '1', 0),
(171, 0, 'dashboard_recent', 'dashboard_recent_sort_order', '8', 0),
(172, 0, 'dashboard_activity', 'dashboard_activity_width', '4', 0),
(173, 0, 'dashboard_recent', 'dashboard_recent_width', '8', 0),
(174, 0, 'report_customer_activity', 'report_customer_activity_status', '1', 0),
(175, 0, 'report_customer_activity', 'report_customer_activity_sort_order', '1', 0),
(176, 0, 'report_customer_order', 'report_customer_order_status', '1', 0),
(177, 0, 'report_customer_order', 'report_customer_order_sort_order', '2', 0),
(178, 0, 'report_customer_reward', 'report_customer_reward_status', '1', 0),
(179, 0, 'report_customer_reward', 'report_customer_reward_sort_order', '3', 0),
(180, 0, 'report_customer_search', 'report_customer_search_sort_order', '3', 0),
(181, 0, 'report_customer_search', 'report_customer_search_status', '1', 0),
(182, 0, 'report_customer_transaction', 'report_customer_transaction_status', '1', 0),
(183, 0, 'report_customer_transaction', 'report_customer_transaction_status_sort_order', '4', 0),
(184, 0, 'report_sale_tax', 'report_sale_tax_status', '1', 0),
(185, 0, 'report_sale_tax', 'report_sale_tax_sort_order', '5', 0),
(186, 0, 'report_sale_shipping', 'report_sale_shipping_status', '1', 0),
(187, 0, 'report_sale_shipping', 'report_sale_shipping_sort_order', '6', 0),
(188, 0, 'report_sale_return', 'report_sale_return_status', '1', 0),
(189, 0, 'report_sale_return', 'report_sale_return_sort_order', '7', 0),
(190, 0, 'report_sale_order', 'report_sale_order_status', '1', 0),
(191, 0, 'report_sale_order', 'report_sale_order_sort_order', '8', 0),
(192, 0, 'report_sale_coupon', 'report_sale_coupon_status', '1', 0),
(193, 0, 'report_sale_coupon', 'report_sale_coupon_sort_order', '9', 0),
(194, 0, 'report_product_viewed', 'report_product_viewed_status', '1', 0),
(195, 0, 'report_product_viewed', 'report_product_viewed_sort_order', '10', 0),
(196, 0, 'report_product_purchased', 'report_product_purchased_status', '1', 0),
(197, 0, 'report_product_purchased', 'report_product_purchased_sort_order', '11', 0),
(198, 0, 'report_marketing', 'report_marketing_status', '1', 0),
(199, 0, 'report_marketing', 'report_marketing_sort_order', '12', 0),
(200, 0, 'developer', 'developer_theme', '1', 0),
(201, 0, 'developer', 'developer_sass', '1', 0),
(202, 0, 'config', 'config_email', 'dergachev.dmitriy@gmail.com', 0),
(203, 0, 'config', 'config_encryption', '2IXNQNF6QPw3cZeNuF1Vg94VDaaqA5Wit8HcLi2eixUjAgGTzyJ7Fg3PQP12P7oJHIbd8Cc8b5vqG1o3Sp7BtIJqYYuwfwAetLDkH2bXUnAVMb656n3bKCS2fdnE7NeKyVUKaNTMak1wXLBf8CTjl9JkXTltcbR18j1bc6atn7097keefIBBfXvfMdf7OcZ53AchHZDUOnT0zpr2oOg1G5x7PDttgkEKbgVGxNLN8GRlCWL3ZnJb46zIIshzdCYmhTGS1jYfZq5FK5JCQyTrVcmjvAkrbVNcNygnyjTXym9e7WE80Eue54LhN8vX0SbBQN6pdjv9bIfyKATjMEDWEGIoNEaFfiwzyoKKYOVpWXU7A3a8VYybSkwF3uClSikWpncPgNvoGoFhsHrQPvldX8MuUn9C5eKqfNAPific8Uddexe5stKas8UacdSl6xvPsmSimGkgT0mrqthMpxa2VKdtgyYcH9eMBZc5FiIci3E7JR0uCJJtPXM7RTMEE7ORW9zLtvZnFUwvTjl4xTQCw9MVaAGJ8V04Gp6pFxERetoiUv7YlVrFxvoNzPiaZU8oBQFF30jEaKlEaPOWB0C873gtJiktoVJf7CEN7bzI6wujbMXnNROWXtx4nF7BB7xAgiTqPo3NsEJ7QgTiNqtyuofc1aSI3KAgWToFOPLJ1X2ezJMRAKro9ACB5AZznMVXoTnMewAjb0I0agp3xckf7BmUQ657wNzdhn49nFkj4id3SfDlT0zqhrOZqba5CfMCtGjhJ00U3BBwUg2x8Lpinkt75iCB9ctUZiGKjm4nG5Vu5asxsugQDsJxRg2S0gwY759XABUv0qEVc2fdC5aBkao8PtUF52DcPEZaa7pJsLxwMtsLYQCKwT6henAOuUW3UCUoGsdH3cJDz5sxeSQa3TiUtTUVtWtasQCHI7s12M1KI7cVHSJAprAYRKNg7ehLhxm541lhe6hdbOjYZr1MsLxb1vHvAaKKbJmG5vt01N5RZIk7RcT6pZSjSlpDWmt0', 0),
(204, 0, 'config', 'config_api_id', '1', 0);
